set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CROSS_CHAIN_PATH  arm-linux-gnueabihf-)
set(CMAKE_C_COMPILER ${CROSS_CHAIN_PATH}gcc)
set(CMAKE_CXX_COMPILER ${CROSS_CHAIN_PATH}g++)

# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
