// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Include your device-specific headers, and edit functions below
// #include "hal.h"

#include "mongoose_glue.h"

void glue_init(void) {
    MG_DEBUG(("Custom init done"));
}

static struct leds s_leds = {false, false, false, false, 0, 0, 0, 0, 100, 100, 100, 100};
void glue_get_leds(struct leds *data) {
    *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
    s_leds = *data; // Sync with your device
}

static struct state s_state = {30, 50};
void glue_get_state(struct state *data) {
    *data = s_state;  // Sync with your device
}
void glue_set_state(struct state *data) {
    s_state = *data; // Sync with your device
}